# pi5-deployer/.github/workflows/deploy-to-pi5.yml
name: Deploy to Pi5 Fleet

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: "Full name of the image in GHCR (leave blank to use env.IMAGE_NAME)"
        required: false
        type: string
        default: ""
      container-name:
        description: "Name to give the running Docker container"
        required: true
        type: string
      host-port:
        description: "Port on the Pi host to map to the container"
        required: true
        type: string
      container-port:
        description: "Port the application listens on inside the container"
        required: true
        type: string
      tag:
        description: "Image tag to deploy (e.g., 'latest', 'v1.0.0')"
        required: false
        type: string
        default: "latest"
      extra-args:
        description: "Any extra Docker run arguments (e.g., '--device /dev/video0')"
        required: false
        type: string

jobs:
  deploy-to-pi:
    runs-on: [self-hosted, pi5, app_model_cd]
    permissions:
      packages: read

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve IMAGE_NAME (input > env fallback)
        id: resolve_image
        shell: bash
        run: |
          INPUT_NAME="${{ inputs.image-name }}"
          if [ -n "$INPUT_NAME" ]; then
            NAME="$INPUT_NAME"
          else
            NAME="${{ env.IMAGE_NAME }}"
          fi
          echo "IMAGE_NAME=$NAME" >> "$GITHUB_OUTPUT"
          echo "Resolved IMAGE_NAME=$NAME"

      - name: Get Docker image ref planned for deployment
        id: image-ref
        run: |
          FULL_IMAGE_REF="${{ steps.resolve_image.outputs.IMAGE_NAME }}:${{ inputs.tag }}"
          echo "FULL_IMAGE_REF=$FULL_IMAGE_REF" >> "$GITHUB_OUTPUT"
          echo "Pulling image: $FULL_IMAGE_REF"

      - name: Pull Docker image from GHCR
        run: docker pull ${{ steps.image-ref.outputs.FULL_IMAGE_REF }}

      - name: Stop and remove old container (if exists)
        run: |
          docker stop ${{ inputs.container-name }} || true
          docker rm ${{ inputs.container-name }} || true

      - name: Verify model mount directory exists in Pi
        run: |
          test -d /opt/edge/models || { echo "Missing /opt/edge/models"; exit 1; }
          ls -l /opt/edge/models || true
          readlink -f /opt/edge/models/current.onnx || echo "Note: current.onnx not set yet"

      - name: Run new container
        run: |
          docker run -d \
            --name ${{ inputs.container-name }} \
            --restart unless-stopped \
            -v /opt/edge/models:/opt/edge/models:ro \
            -p ${{ inputs.host-port }}:${{ inputs.container-port }} \
            ${{ inputs.extra-args }} \
            ${{ steps.image-ref.outputs.FULL_IMAGE_REF }}

      - name: Verify deployment
        run: |
          echo "Container status:"
          docker ps --filter "name=${{ inputs.container-name }}"
          echo ""
          echo "Recent logs:"
          docker logs --tail 50 ${{ inputs.container-name }} || echo "Container might still be starting up..."
