# .github/workflows/deploy-to-pi5.yml
name: Deploy Image from GHCR to Pi5

on:
  workflow_dispatch:
    inputs:
      # Optional: keep this if you want to manually override at dispatch time
      image-name:
        description: "Image from GHCR to deploy(leave blank to use repo variable IMAGE_NAME)"
        required: false
        type: string
        default: ""
      container-name:
        description: "Application container name to create at Pi(leave blank to use .env APP_NAME)"
        required: false
        type: string
        default: ""
      host-port:
        description: "Pi Host port (leave blank to use .env HOST_PORT)"
        required: false
        type: string
        default: ""
      container-port:
        description: "Container port (leave blank to use .env APP_PORT)"
        required: false
        type: string
        default: ""
      tag:
        description: "Image tag"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  packages: read

jobs:
  deploy-to-pi:
    runs-on: [self-hosted, pi5, app_model_cd]

    steps:
      - uses: actions/checkout@v4

      - name: Load .env (if present)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f .env ]; then
            # Only source lines like VAR=VALUE
            if grep -q '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=' .env; then
              set -a
              # shellcheck disable=SC1091
              . ./.env
              set +a
            else
              echo "Found .env, but no VAR=VALUE lines were detected. Skipping."
            fi
          fi
          echo "APP_NAME=${APP_NAME:-}"   >> "$GITHUB_ENV"
          echo "HOST_PORT=${HOST_PORT:-}" >> "$GITHUB_ENV"
          echo "APP_PORT=${APP_PORT:-}"   >> "$GITHUB_ENV"

      - name: Resolve deployment parameters
        id: resolve
        shell: bash
        run: |
          set -euo pipefail

          # Inputs (image-name is optional; remove these 2 lines if you don't want it at all)
          IN_IMAGE="${{ inputs.image-name }}"
          IN_TAG="${{ inputs.tag }}"

          # Repo variable (must be set if no input is provided)
          VAR_IMAGE="${{ vars.IMAGE_NAME }}"

          # Decide image name:
          # 1) Use manual input if provided
          # 2) Else use repo variable IMAGE_NAME
          if [ -n "$IN_IMAGE" ]; then
            IMAGE_NAME="$IN_IMAGE"
          else
            if [ -z "$VAR_IMAGE" ]; then
              echo "ERROR: Repository variable IMAGE_NAME is not set, and no image-name input was provided."
              echo "Please set Settings → Variables → Repository variables → IMAGE_NAME (e.g., 'ghcr.io/<owner>/<repo>' or just '<repo>')."
              exit 1
            fi
            IMAGE_NAME="$VAR_IMAGE"
          fi

          # If IMAGE_NAME is bare (no registry prefix), prefix with ghcr.io/<owner>/
          if [[ "$IMAGE_NAME" != ghcr.io/* ]]; then
            IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"
          fi

          TAG="${IN_TAG:-latest}"
          FULL_IMAGE_REF="${IMAGE_NAME}:${TAG}"

          # Container config: inputs > .env > defaults
          CONTAINER_NAME="${{ inputs.container-name }}"
          if [ -z "$CONTAINER_NAME" ]; then
            CONTAINER_NAME="${APP_NAME:-pcb-app}"
          fi

          HOST_PORT_VAL="${{ inputs.host-port }}"
          if [ -z "$HOST_PORT_VAL" ]; then
            HOST_PORT_VAL="${HOST_PORT:-8080}"
          fi

          CONT_PORT_VAL="${{ inputs.container-port }}"
          if [ -z "$CONT_PORT_VAL" ]; then
            CONT_PORT_VAL="${APP_PORT:-8080}"
          fi

          # Validate ports are numeric
          [[ "$HOST_PORT_VAL" =~ ^[0-9]+$ ]] || { echo "HOST_PORT must be numeric"; exit 1; }
          [[ "$CONT_PORT_VAL" =~ ^[0-9]+$ ]] || { echo "CONTAINER_PORT must be numeric"; exit 1; }

          {
            echo "IMAGE_NAME=$IMAGE_NAME"
            echo "CONTAINER_NAME=$CONTAINER_NAME"
            echo "HOST_PORT=$HOST_PORT_VAL"
            echo "CONTAINER_PORT=$CONT_PORT_VAL"
            echo "TAG=$TAG"
            echo "FULL_IMAGE_REF=$FULL_IMAGE_REF"
          } >> "$GITHUB_OUTPUT"

          {
            echo "### Deployment parameters"
            echo ""
            echo "| Key | Value |"
            echo "|---|---|"
            echo "| Image | \`${FULL_IMAGE_REF}\` |"
            echo "| Container name | \`${CONTAINER_NAME}\` |"
            echo "| Host port | \`${HOST_PORT_VAL}\` |"
            echo "| Container port | \`${CONT_PORT_VAL}\` |"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull "${{ steps.resolve.outputs.FULL_IMAGE_REF }}"

      - name: Stop and remove old container (if exists)
        shell: bash
        run: |
          docker stop "${{ steps.resolve.outputs.CONTAINER_NAME }}" || true
          docker rm   "${{ steps.resolve.outputs.CONTAINER_NAME }}" || true

      - name: Verify model mount directory exists on Pi
        shell: bash
        run: |
          test -d /opt/edge/models || { echo "Missing /opt/edge/models"; exit 1; }
          ls -l /opt/edge/models || true
          readlink -f /opt/edge/models/current.onnx || echo "Note: current.onnx not set yet"

      - name: Run new container
        shell: bash
        run: |
          set -euo pipefail
          EXTRA='${{ inputs.extra-args }}'
          if [ -n "$EXTRA" ]; then
            EXTRA_ARR=($EXTRA)
          else
            EXTRA_ARR=()
          fi

          docker run -d \
            --name "${{ steps.resolve.outputs.CONTAINER_NAME }}" \
            --restart unless-stopped \
            -v /opt/edge/models:/opt/edge/models:ro \
            -p ${{ steps.resolve.outputs.HOST_PORT }}:${{ steps.resolve.outputs.CONTAINER_PORT }} \
            -l org.opencontainers.image.source=${{ github.repository }} \
            -l org.opencontainers.image.revision=${{ github.sha }} \
            "${EXTRA_ARR[@]}" \
            "${{ steps.resolve.outputs.FULL_IMAGE_REF }}"

      - name: Verify deployment
        shell: bash
        run: |
          echo "Container status:"
          docker
