name: Model CD - Ship latest ONNX model Pi

on:
  # Auto-run when a new Release is published in ANY repository
  release:
    types: [published]
  # Also allow manual runs with configurable source repo
  workflow_dispatch:
    inputs:
      model-repo:
        description: 'Source repo of Github Release where .ONXX model is present. Leave empty to pick the repo of this workflow'
        required: false
        default: ''
      pi-proj-repo:
        description: 'Project directory at Pi end. Leave empty to pick the Project repo name'
        required: false
        default: ''

permissions:
  contents: read

concurrency:
  group: model-cd
  cancel-in-progress: true

jobs:
  validate:
    name: Validate ONNX (from Release)
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.download.outputs.model_name }}
      model_sha:  ${{ steps.hash.outputs.model_sha }}
      short_sha:  ${{ steps.hash.outputs.short_sha }}
      utc_stamp:  ${{ steps.utc.outputs.utc_stamp }}
      source_repo: ${{ steps.repo-config.outputs.source_repo }}
      source_tag: ${{ steps.rel.outputs.tag_name }}
      repo_name: ${{ steps.repo-config.outputs.repo }}
      pi_project_name: ${{ steps.repo-config.outputs.pi_project_name }}
    steps:
      - name: Checkout repository (for workflow context)
        uses: actions/checkout@v4

      - name: Configure source repository and project name logic
        id: repo-config
        shell: bash
        run: |
          # If user provided empty input for model-repo, use current repository
          if [ -z "${{ github.event.inputs.model-repo }}" ]; then
            SOURCE_REPO="$GITHUB_REPOSITORY"
            echo "Using current repository: $SOURCE_REPO"
          else
            SOURCE_REPO="${{ github.event.inputs.model-repo }}"
            echo "Using user-specified repository: $SOURCE_REPO"
          fi
          
          # Extract owner and repo from the source
          IFS='/' read -r OWNER REPO <<< "$SOURCE_REPO"
          
          # Validate the repository format
          if [ -z "$OWNER" ] || [ -z "$REPO" ]; then
            echo "Invalid repository format. Expected: owner/repo"
            exit 1
          fi
          
          # Determine project directory name
          if [ -z "${{ github.event.inputs.pi-proj-repo }}" ]; then
            PI_PROJECT_NAME="$REPO"
            echo "Using repository name as project directory: $PI_PROJECT_NAME"
          else
            PI_PROJECT_NAME="${{ github.event.inputs.pi-proj-repo }}"
            echo "Using user-specified project directory: $PI_PROJECT_NAME"
          fi
          
          # Sanitize project name (remove any path characters for safety)
          PI_PROJECT_NAME=$(echo "$PI_PROJECT_NAME" | sed 's/[./]//g')
          echo "Sanitized project name: $PI_PROJECT_NAME"
          
          echo "source_repo=$SOURCE_REPO" >> $GITHUB_OUTPUT
          echo "owner=$OWNER" >> $GITHUB_OUTPUT
          echo "repo=$REPO" >> $GITHUB_OUTPUT
          echo "pi_project_name=$PI_PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Get latest release & select .onnx asset
        id: rel
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          script: |
            const owner = '${{ steps.repo-config.outputs.owner }}';
            const repo = '${{ steps.repo-config.outputs.repo }}';
            const sourceRepo = '${{ steps.repo-config.outputs.source_repo }}';
            const piProject = '${{ steps.repo-config.outputs.pi_project_name }}';
            
            console.log(`Looking for latest release in: ${sourceRepo}`);
            console.log(`Project directory on Pi: ${piProject}`);
            
            try {
              // Get the latest release from the specified repository
              const rel = await github.rest.repos.getLatestRelease({ owner, repo });
              console.log(`Found release: ${rel.data.tag_name}`);
              
              // Find ONNX assets in the release
              const assets = rel.data.assets || [];
              const onnxAssets = assets.filter(a => a.name && a.name.toLowerCase().endsWith('.onnx'));
              
              if (onnxAssets.length === 0) {
                core.setFailed(`No .onnx assets found in latest release "${rel.data.tag_name}" of ${sourceRepo}`);
                return;
              }
              
              // For now, use the first ONNX asset found
              const onnx = onnxAssets[0];
              console.log(`Selected ONNX asset: ${onnx.name} (${onnxAssets.length} total ONNX files found)`);
              
              // Set outputs for downstream steps
              core.setOutput('tag_name', rel.data.tag_name);
              core.setOutput('asset_id', String(onnx.id));
              core.setOutput('asset_name', onnx.name);
              core.setOutput('asset_count', String(onnxAssets.length));
              
              // If multiple ONNX files, warn but continue with first one
              if (onnxAssets.length > 1) {
                console.warn(`⚠️ Multiple ONNX files found. Using first file: ${onnx.name}`);
                console.warn(`   Consider updating the workflow to handle multiple models if needed.`);
              }
              
            } catch (error) {
              if (error.status === 404) {
                core.setFailed(`No releases found in repository: ${sourceRepo}. Please check if the repository exists and has releases.`);
              } else {
                core.setFailed(`Error accessing repository ${sourceRepo}: ${error.message}`);
              }
            }

      - name: Download ONNX asset from latest release
        id: download
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -euo pipefail
          ASSET_ID='${{ steps.rel.outputs.asset_id }}'
          ASSET_NAME='${{ steps.rel.outputs.asset_name }}'
          SOURCE_REPO='${{ steps.repo-config.outputs.source_repo }}'
          PI_PROJECT='${{ steps.repo-config.outputs.pi_project_name }}'
          
          echo "Downloading asset: $ASSET_NAME (id=$ASSET_ID)"
          echo "Source repository: $SOURCE_REPO"
          echo "Pi project directory: $PI_PROJECT"
          
          # Download from the specified repository
          curl -sSL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/octet-stream" \
            -o "$ASSET_NAME" \
            "https://api.github.com/repos/${SOURCE_REPO}/releases/assets/$ASSET_ID"
          
          echo "MODEL_PATH=$ASSET_NAME" >> $GITHUB_ENV
          echo "model_name=$ASSET_NAME" >> $GITHUB_OUTPUT

      # ... (rest of the validate job steps remain the same - just showing the changed parts)

  deliver:
    name: Deliver to Pi and flip current.onnx
    needs: validate
    runs-on: [self-hosted, app_model_cd]
    steps:
      - name: Download validated bundle
        uses: actions/download-artifact@v4
        with:
          name: validated-model

      - name: Show downloaded files and source info
        run: |
          echo "Model source repository: ${{ needs.validate.outputs.source_repo }}"
          echo "Model source release: ${{ needs.validate.outputs.source_tag }}"
          echo "Target repository folder: ${{ needs.validate.outputs.repo_name }}"
          echo "Pi project directory: ${{ needs.validate.outputs.pi_project_name }}"
          ls -l

      - name: Create project directory structure on Pi
        id: setup-dirs
        shell: bash
        run: |
          PI_PROJECT_NAME="${{ needs.validate.outputs.pi_project_name }}"
          TARGET_BASE="/opt/edge/$PI_PROJECT_NAME"
          
          echo "Creating project structure for: $PI_PROJECT_NAME"
          echo "Base directory: $TARGET_BASE"
          echo "Source repository: ${{ needs.validate.outputs.source_repo }}"
          
          # Create all required directories
          sudo mkdir -p "$TARGET_BASE/models"
          sudo mkdir -p "$TARGET_BASE/manifests"
          sudo mkdir -p "$TARGET_BASE/tmp"
          
          # Create deployments.log if it doesn't exist
          sudo touch "$TARGET_BASE/deployments.log"
          
          # Set proper permissions (adjust as needed for your user)
          sudo chown -R $USER:$USER "$TARGET_BASE" || true
          sudo chmod -R 755 "$TARGET_BASE"
          
          echo "Project structure created:"
          ls -la "$TARGET_BASE/"
          
          # Set output for use in subsequent steps
          echo "target_base=$TARGET_BASE" >> $GITHUB_OUTPUT

      - name: Verify project directory exists on Pi
        shell: bash
        run: |
          TARGET_BASE="${{ steps.setup-dirs.outputs.target_base }}"
          PI_PROJECT_NAME="${{ needs.validate.outputs.pi_project_name }}"
          echo "Verifying project directory: $TARGET_BASE"
          echo "Project name: $PI_PROJECT_NAME"
          test -d "$TARGET_BASE" || (echo "Base directory missing"; exit 1)
          test -d "$TARGET_BASE/models" || (echo "Models directory missing"; exit 1)
          test -d "$TARGET_BASE/manifests" || (echo "Manifests directory missing"; exit 1)
          test -d "$TARGET_BASE/tmp" || (echo "Temp directory missing"; exit 1)
          test -f "$TARGET_BASE/deployments.log" || (echo "Deployments log missing"; exit 1)
          echo "✓ All project directories verified"

      # ... (rest of the deliver job steps remain the same, just using the new target_base)

      - name: Stage, move, and atomic switch
        if: steps.idem.outputs.skip != 'true'
        shell: bash
        run: |
          set -e
          FILE="$(find . -maxdepth 4 -type f -name '*.onnx' | head -n1)"
          MODEL_ID="${{ needs.validate.outputs.model_sha }}"
          SHORT="${{ needs.validate.outputs.short_sha }}"
          STAMP="${{ needs.validate.outputs.utc_stamp }}"
          SOURCE_REPO="${{ needs.validate.outputs.source_repo }}"
          MODEL_FILE="${{ needs.validate.outputs.model_name }}"
          MODEL_BASENAME="${MODEL_FILE%.*}"
          PI_PROJECT_NAME="${{ needs.validate.outputs.pi_project_name }}"
          TARGET_BASE="${{ steps.setup-dirs.outputs.target_base }}"
          
          # Use original model name + timestamp + short sha for unique filename
          FINAL="$TARGET_BASE/models/${MODEL_BASENAME}-${STAMP}-${SHORT}.onnx"
          MANIFEST_FINAL="$TARGET_BASE/manifests/${MODEL_BASENAME}-${MODEL_ID}.json"

          echo "Deploying model from: $SOURCE_REPO"
          echo "Pi project directory: $PI_PROJECT_NAME"
          echo "Original model name: $MODEL_FILE"
          echo "Target base: $TARGET_BASE"
          echo "Final path: $FINAL"

          # Stage the file
          STAGE="$TARGET_BASE/tmp/$MODEL_ID"
          echo "Staging at: $STAGE"
          sudo mkdir -p "$STAGE"
          sudo cp "$FILE" "$STAGE/model.onnx"
          sudo cp manifest.json "$STAGE/manifest.json"

          # Move to final location
          sudo mv "$STAGE/model.onnx" "$FINAL"
          sudo mv "$STAGE/manifest.json" "$MANIFEST_FINAL"
          sudo rmdir "$STAGE" || true

          # Update symlinks
          if [ -L "$TARGET_BASE/current.onnx" ]; then
            OLD="$(readlink -f "$TARGET_BASE/current.onnx")"
            sudo ln -sfn "$OLD" "$TARGET_BASE/previous.onnx"
          fi

          sudo ln -sfn "$FINAL" "$TARGET_BASE/current.onnx"

          # Log the deployment
          echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) DEPLOY model_id=${MODEL_ID} source=${SOURCE_REPO} project=${PI_PROJECT_NAME} file=$(basename "$FINAL")" | sudo tee -a "$TARGET_BASE/deployments.log" > /dev/null

          echo "current.onnx -> $(readlink -f "$TARGET_BASE/current.onnx")"
          [ -L "$TARGET_BASE/previous.onnx" ] && echo "previous.onnx -> $(readlink -f "$TARGET_BASE/previous.onnx")" || echo "previous.onnx not set (first deploy)"

      # ... (rest of the steps remain similar with updated paths)

      - name: List project directory (for sanity)
        run: |
          TARGET_BASE="${{ steps.setup-dirs.outputs.target_base }}"
          PI_PROJECT_NAME="${{ needs.validate.outputs.pi_project_name }}"
          echo "Project: $PI_PROJECT_NAME"
          echo "Model source: ${{ needs.validate.outputs.source_repo }}"
          echo "Base directory: $TARGET_BASE"
          echo "=== Directory Structure ==="
          ls -la "$TARGET_BASE/"
          echo "=== Models ==="
          ls -la "$TARGET_BASE/models/" || echo "No models directory"
          echo "=== Manifests ==="
          ls -la "$TARGET_BASE/manifests/" || echo "No manifests directory"
          echo "=== Symlinks ==="
          ls -la "$TARGET_BASE/current.onnx" 2>/dev/null || echo "No current.onnx symlink"
          ls -la "$TARGET_BASE/previous.onnx" 2>/dev/null || echo "No previous.onnx symlink"